responsively-org/responsively-app

desktop-app/app/main.dev.js
I believe I have fixed `open-url` feature on `Windows`. I have tested on both `Windows` and `Mac`. 
And this is related https://github.com/manojVivek/responsively-app/issues/155
Fix https://github.com/manojVivek/responsively-app/issues/155
Please let me know if I am missing something or something can be improved.
=> fix windows open-url

desktop-app/app/shortcuts.html
This only happens in the production build 🤷🏻‍♂️
Before:
After this fix:
- Fix: set `max-height` property to `ul` inside `shortcuts.html`
=> Fix ugly global scrollbar in hotkeys dialog

desktop-app/app/components/Renderer/index.js, desktop-app/app/components/WebView/index.js
Hello, in this PR I would like to add changes on each device's dimension display (WxH) depending on the orientation it's currently on, triggered by flip orientation, if that makes sense or possible. thanks before. 😅
=> Request dimensions display changes

desktop-app/app/components/DevicesPreviewer/style.module.css, desktop-app/app/components/Drawer/styles.css, desktop-app/app/containers/Browser/index.js
Made the drawer not shrinkable so it's still usable in horizontal layout.
- increase the bottom padding on the devices container because it was really close to the new bottom app bar
- change overflow from `scroll`to `auto` on the devices container so the scrollbar only shows up when needed
fix #225
=> Drawer shrinking in horizontal layout

desktop-app/app/app.global.css, desktop-app/app/components/Header/style.module.css, desktop-app/app/containers/Browser/index.js, desktop-app/app/layout.css
Prevent the main content div from growing more than its container and thus hiding the scrollbar behind the status bar.
I also made the devices tabs scrollable, they were shrinking and became ugly on small screen.
fix #233
=> Fix horizontal scrolling

desktop-app/app/components/Drawer/styles.css, desktop-app/app/containers/Browser/index.js
Previously, width was used in animation, this caused strange animation when opening the Drawer.
This solution uses the property of margin and achieves smoother animation.
=> Fix animation when opening the Drawer

desktop-app/app/components/ExtensionsManager/index.js
**Changes**
- Validate the extension id (allowing only lowercase characters), once the user presses enter or click on Add button.
- Shows the error message if the input is invalid.
Fixes https://github.com/manojVivek/responsively-app/issues/240
=> Validate the extension id 

desktop-app/app/app.global.css, desktop-app/app/components/Header/style.module.css
**Summary**
When the devices are on maximized mode the zoom controls are hidden behind the tabs
**Current behavior**
**With fixes applied**
Edit:
Just saw that this was reported a few days ago and already assigned to someone else. It's ok if you want to discard my PR.
Closes #313
=> fix: Solves zoom toolbar being hidden behind the devices tabs

desktop-app/app/containers/Root.js, desktop-app/app/reducers/browser.js
- **remember zoom level**
- **add zoom level increment shortcut**
In Mac the shortcut is `Command` + `+`. The same shortcut for decrement already exists (`Command` + `-`).
Closes #320
=> feat(zoomLevel): remember zoom level

desktop-app/app/components/WebView/index.js
As suggested on issue #255 comment https://github.com/manojVivek/responsively-app/issues/255#issuecomment-665766060 a better approach to hiding the scrollbar on mobile devices is to hide it on all elements.
=> fix(desktop-app): on mobile devices hide scrollbar on all elements

website/js/mrare/contributors.js, website/pages/assets/css/custom.css, website/pages/index.html
Fix #397 
The PR creates a new section above the footer, displaying all github contributors. 
Changes: 
* Add new `<section>` tag above the footer in `index.html`
* Write script to fetch all contributors and generate HTML code in `contributors.js`
* Write styling rules in `custom.css`
=> Add Github contributors list

desktop-app/app/components/Addressinput/index.js, desktop-app/app/components/UrlSearchResults/index.js
Aside from fixing the bug reported in #410 this PR fixes other errors too:
- This PR
- Current app
- This PR
- Current app
- This PR
- Current app
- This PR
Fixes #410
=> fix(desktop-app): improve address bar suggestions

desktop-app/app/components/ToggleTouch/index.js
This is a fix to issue https://github.com/responsively-org/responsively-app/issues/388
The cause of the bug was that the state of the pointer (mouse/touch) was updated as the pointer left the button. With this fix, the state is updated on mouse movement within the button, giving it a more responsive feel.
=> Fixed persistent hover effect

desktop-app/app/actions/browser.js, desktop-app/app/components/ZoomInput/index.js, desktop-app/app/constants/index.js, desktop-app/app/containers/Root.js, desktop-app/app/reducers/browser.js, desktop-app/app/utils/browserUtils.js
**What's in the Pull Request:**
- Fixes issues where the user was able to zoom to negative values which in turn broke the UI. 
- While testing, I found an scenario where if the user closes the app while having negative zoom, on re-open the zoom level was maintained because it was saved to user preferences. This meant the app was unusable on start up. Fixed that as well.
**Fix:**
- Added a function to normalize zoom such that it stays within the threshold.
- Added default, min and a max zoom level constants to ensure things work between scroll zoom and toolbar zoom.
**Scenarios Tested:**
- Scrolled beyond min and max permitted zoom levels.
- Reset zoom using keyboard short cut `Ctrl + 0`.
- Used +/- in the toolbar to reach min and max zoom level.
**Screenshot/Video**
=> Fix issue with zooming using scroll going negative and breaking UI

desktop-app/app/components/NetworkProxy/ProxyManager/index.js
**Light Theme**
Before:
After:
**Dark Theme**
Before:
After:
=> fix link on proxy manager modal on light theme

desktop-app/app/components/WebView/index.js, desktop-app/app/components/WebView/style.module.css, desktop-app/app/utils/generalUtils.js
Alert user that ssl validation can be disabled whenever the page load fails because of ssl validation.
These commits implements changes suggested under Issue #403.
I have test my work using the web site badssl.com. This site provide urls that produce ssl errors.you can use them and check for result.
here are the errors i've tested:
-200:CERT_COMMON_NAME_INVALID
The server responded with a certificate whose common name did not match the host name.
tested using this url https://wrong.host.badssl.com/
-201:CERT_DATE_INVALID
The server responded with a certificate that, by our clock, appears to either not yet be valid or to have expired.
tested using this url expired.badssl.com
-202:CERT_AUTHORITY_INVALID	
The server responded with a certificate that is signed by an authority we don't trust. …
=>  alert user that ssl validation can be disabled

desktop-app/app/components/DeviceManager/index.js
Closes: #509
Closes the dev tools before opening the device drawer.
=> bugfix(desktop-app): fix dev tolls overlapping device drawer

README.md
Brew has updated to only allow `brew install --cask`.
```sh
Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
```
=> Update brew cask command

desktop-app/app/containers/Browser/index.js
Fixes #553 
This PR fixes a scenario where the layout is set to horizontal and the content overflows horizontally but there is no horizontal scrollbar. Tested on Windows and with the same specs as reported in the issue (re devices and zoom). Also tested with other devices and zoom properties to ensure the vertical and horizontal scrollbars appear and disappear as expected, depending on the size of the content.
**Scenario 1:**
5 devices, zoom 60%, content overflows horizontally and vertically => both scrollbars appear
**Scenario 2:**
3 devices, zoom 50%, content fits inside the container => no scrollbar visible
**Scenario 3:**
5 devices, zoom 30%, content overflows horizontally => horizontal scrollbar appears
**Scenario 4:**
2 devices, zoom 50%, content overflows vertically => vertical …
=> #553 - Fix missing horizontal scrollbar

desktop-app/app/components/UserPreferences/index.js, desktop-app/app/components/UserPreferences/useStyles.js, desktop-app/app/components/WebView/index.js, desktop-app/app/reducers/browser.js
Resolves #531 
The solution adds a user preference checkbox to allow the user to enable/disable the spellchecking that is active after entering design mode. Right now, toggling the setting does **not** have effect after the webview/device window has already been created. A restart of the app can work around that (there's a note in the user preferences view - the user will probably only touch this once).
Tested this based on the description and video from the referenced issue: checking the spellcheck functionality by enabling Design Mode in the app. Tested in WIndows 10 only.
=> Add toggle spellcheck

desktop-app/app/actions/browser.js, desktop-app/app/components/UserPreferences/index.js, desktop-app/app/constants/values.js, desktop-app/app/main.dev.js, desktop-app/app/reducers/browser.js, desktop-app/app/settings/migration.js, desktop-app/app/utils/navigatorUtils.js, desktop-app/app/utils/urlUtils.js
resolves #521 
Added a select to User Preferences to set between blank page and homepage as startup page when app launches
❗ An scrollbar appeared, maybe it's time to reorder the left menu 👀
I tried with a checkbox like "Use blank page instead of homepage when app launches" but it take two lines and the scrollbar appeared too
and another version:
I think we could go like this and then reorder the whole sidebar
=> Add option to switch between blank page and homepage when app launches

desktop-app/app/components/AppNotification/styles.module.css
resolves #584 
Responsively notification get behind of <webview/> when navigation resulted in error. 
This PR just fix the notification `z-index` value (`[notification z-index] = [webview z-index] + 1`)
**BEFORE**:
**AFTER**
=> fix notification styles

desktop-app/app/main.dev.js
resolves #540 and resolves #608
After the changes made on #586, the issue #540 should have been resolved. Testing it I found other problems detecting when the argument passed as a parameter to the app was an URL or a file.
After these changes, at least in Windows I have been able to verify that #540 is resolved. It would be good to test it on mac and linux (cc: @manojVivek )
I used the following `gulpfile.js` on Windows
```js
const { series } = require('gulp');
const browserSync = require('browser-sync').create();
function serve(done) {
browserSync.init({
port: 3000,
server: true,
startPath: 'index.html'
// browser: "responsivelyapp",
browser: "%LOCALAPPDATA%\\Programs\\Responsively-App\\ResponsivelyApp.exe"
});
done();
}
function defaultTask(done) {
const startupTasks = series(
serve,
); …
```
=> fix browserSync usage

desktop-app/app/constants/chromeEmulatedDevices.js
Fixes missing default 16-9 TOUCH display for industry prototyping.
Was missing a default 16-9 multi-touch display for industry use. I've added the one that we use in our research institute for prototyping assembly assistance applications. Default is not shown to not slow down initialization. 
Really nice app so far and I will probably tell my research colleagues about it.
=> Add Fujitsu E24-9 TOUCH Display

desktop-app/app/actions/browser.js, desktop-app/app/components/UserPreferences/index.js, desktop-app/app/components/UserPreferences/useStyles.js, desktop-app/app/main.dev.js, desktop-app/app/reducers/browser.js
#656 
Added buttons to export and import user preferences. I preferred to do the download and upload of the json file from the main process, from the renderer process there is a problem with the redux extension in development mode (I think it is a better solution to do it from the main process). I would love to read the proposals to improve UX to export / import buttons and about the configuration file which is currently a JSON.
[Uploading a config file with 3 custom devices and darkmode](https://www.loom.com/share/31a609e9ba394336a1d0579a11bb66c4)
I tested exporting and importing configurations between windows (10) and Linux (Debian bullseye)
=> Export and import preferences

desktop-app/app/components/DevToolsResizer/index.js
Fixes #530 
Change the resizer size and toolbar position to fix the non-clickable icons when devtools are right-docked.
=> Fix - Problem with right-docked devtools

desktop-app/app/components/WebView/index.js, desktop-app/app/preload.js
resolves #696
set `window._bot = true` on each device
=> define a variable on the window object to help analytics

desktop-app/src/renderer/components/DeviceManager/index.tsx
fixes #869.
Search input is now stored "raw", input sanitization is done before filtering.
Whitespace characters can now be entered as expected, filtering result should not be affected.
=> fix: allow whitespaces in device search (#869)

desktop-app/src/main/main.ts
Resolves issues with browser-sync such as scrolling, for websites with strict Content Security Policy (CSP) rules that prevent the injected browser-sync script from loading.
Fixes: #710 and #860 
Injects the BROWSER_SYNC_HOST to the allowed Content-Security-Policy origins header
=> Fix browser-sync issue related to Content Security Policy (CSP)

desktop-app/package.json, desktop-app/src/common/constants.ts, desktop-app/src/renderer/components/Previewer/Device/Toolbar.tsx, desktop-app/src/renderer/components/Previewer/Device/index.tsx, desktop-app/src/renderer/components/Previewer/IndividualLayoutToolBar/index.tsx, desktop-app/src/renderer/components/Previewer/IndividualLayoutToolBar/styles.css, desktop-app/src/renderer/components/Previewer/index.tsx
Fixes: #883
As per the issue, there was a need to have an individual layout view. I have addressed this by adding a button in the Toolbar section of the Device. Users can now click this button to enable and disable individual layout view.
I have added the following changes:
1. Added a button on the device toolbar that allows users to enable/disable to an individual layout mode.
2. Implemented a new toolbar for the individual layout mode, enabling users to toggle between multiple devices on the screen.
3. Included a close button for users to exit the individual layout view.
4. Implemented a custom scrollbar to ensure unobstructed visibility of the text.
Additionally, I fixed a breaking change in the handler 'disable-default-window-open-handler' (line 287, Device/index.js) that caused …
=> added feat: enable/disable individual layout view

desktop-app/release/app/package-lock.json, desktop-app/src/renderer/components/ReleaseNotes/index.tsx
This changes resolves #940 
**About the PR :**
Added "Sponsor" button in the ` ReleaseNotes ` component which will take us to the website [sponsor page](https://responsively.app/sponsor/) .
Here is a preview of the Release Notes popup .
Tested the app after adding new button and everything seems to be working properly .
=> add sponsor button in release note popup #940

desktop-app/src/renderer/components/Previewer/Device/index.tsx
This PR simply hides scrollbars on mobile devices.
=> Fix mobile scrollbar

desktop-app/src/renderer/components/Previewer/Device/Toolbar.tsx, desktop-app/src/renderer/components/Previewer/IndividualLayoutToolBar/index.tsx
Screenshot:
Device toolbar
Individual layout tabs:
=> Separated the individual layout icon from the rest of the icons for better visibility and tweaked the individual layout tabs design

desktop-app/src/common/constants.ts, desktop-app/src/main/browser-sync.ts, desktop-app/src/main/main.ts, desktop-app/src/renderer/store/features/renderer/index.ts
Fixes #969 
Hot-reloading for static html/js/css files even if they weren't running on a (local) development server.
[hot_reload_static_web_files.webm](https://github.com/responsively-org/responsively-app/assets/59393936/27f03991-6c64-4466-b1b5-25dfe6d3977a)
=> feature: hot-reloading for static web files

desktop-app/src/main/screenshot/index.ts
- Fixed screenshot not working well for transparent background website [#959]
Fixed by adding below code
```js
...
await WebContents?.executeJavaScript(`
const bgColor = window.getComputedStyle(document.body).backgroundColor;
if (bgColor === 'rgba(0, 0, 0, 0)') {
document.body.style.backgroundColor = 'white';
} 
window.isExecuted = true;
`);
```
- Before 
- After
=> Fixed screenshot transparent website

desktop-app/src/main/screenshot/index.ts
Fixes: #1003 
Capturing screenshots for devices that contain `/` in the name cause the app to get stuck on macOS. As explained on the issue `/` and `:` might cause issues on filenames on macOS therefore causing an exception when attempting to save the file.
=> fix: App is stuck when capturing all webviews on macOS

desktop-app/src/common/deviceList.ts
#1017
#web_issue_1402
fixed viewport size for device S21 FE
=> fixed view port for S21 FE device <danial.mail.gh@gmail.com>

desktop-app/src/renderer/components/Previewer/Device/Toolbar.tsx
Fixes #1064 
As described in the issue, there was a need of refreshing only a specific view without the need of using the console. The current state of the app contains a global refresh button on the left of the URL bar, which triggers a reload for every view in the app.
To fix the issue, a new button is added in the view specific toolbar, that will refresh **that** view without hampering other views.
Test: Changed some element's text in different views (using inspect element) and tried refreshing the views one at a time.
=> [Feature] Refresh Feature for a single view

README.md
added 'users' badge for edge extension in readme.md
The 'users' badge was missing for the edge's extension... Here's my small contribution!
=> added 'users' badge for edge extension in readme.md

desktop-app/src/renderer/components/DeviceManager/DeviceDetailsModal.tsx
- Resolves #922 
- Resolves #749
In `DeviceDetailsModal.tsx`:
- only disable name input if it is not a custom device.
- remove the note informing user that they can not change the custom device's name
- Disallow the ability to change a custom device's name to an existing device's name in the `handleAddDevice` function
-  I added this because it is already the existing behavior when adding a new custom device, and because it creates issues when checking/unchecking custom devices with the same name because the logic in `DeviceLabel.tsx` is still using name instead of id.
=> Add ability to edit a custom device's name

desktop-app/src/renderer/components/ToolBar/AddressBar/index.tsx
Fixes #743 
This PR adds a drop zone functionality for dragging URLs to the URL bar in the app. You can now simply drag URLs from other apps / from one of the webviews, onto Responsively's URL bar.
Can drag URLs from other apps as well as from one of the webviews of Responsively.
=> [Feature] URLs can now be dragged onto the url bar

desktop-app/src/renderer/components/ToolBar/AddressBar/BookmarkButton.tsx
this is not an opened issue, this is the small feature when I used with the app I found out
I found out when you click on bookmark icon and the menu opens, it will never close unless you click the icon again and it was a little bit annoying to me. so I added a function to detect outside click and the close the menu not just by clicking on icon!
https://github.com/responsively-org/responsively-app/assets/113235504/c4acbaf0-2e7c-46da-8002-f3cea1ffe044
=> added  useDetectionOutside for bookmark

desktop-app/src/renderer/components/ToolBar/AddressBar/index.tsx
Resolved the issue of overlapping between URL text and icons within the address bar. The change addresses the problem illustrated below:
Before:
After:
=> Fixed issue #1100

README.md
The broken slack link on the main `README.md` was replaced to the updated Discord channel.
=> Replaced broken slack link to Discord in README.md

desktop-app/package.json, desktop-app/src/main/main.ts, desktop-app/src/main/preload.ts, desktop-app/src/renderer/App.css, desktop-app/src/renderer/AppContent.tsx, desktop-app/src/renderer/components/Toggle/index.tsx, desktop-app/src/renderer/components/ToolBar/Menu/Flyout/Settings/SettingsContent.tsx, desktop-app/src/renderer/titlebar-styles.css, desktop-app/yarn.lock
Fixes #189 
As suggested by @Kidcredo , The [custom-electron-toolbar](https://www.npmjs.com/package/custom-electron-titlebar) package was added to the project to tweak the default toolbar. This made it possible to make the File menu and the Title be in the same space which optimizes the screen space available and more accessible for devices with smaller screen. 
The app's brand color is now used by the custom titlebar.
Previous titlebar
Custom titlebar
=> [Feature] Added a Custom Titlebar

desktop-app/src/renderer/components/DropDown/index.tsx, desktop-app/src/renderer/components/Previewer/Device/Toolbar.tsx, desktop-app/src/renderer/store/features/renderer/index.ts
#1075 Accessibility simulator menu
This PR adds a menu, dropdown, to apply XSLT filters to one of the webviews to simulate the experience of people with visual impairments and color deficiencies.
Things to consider:
- Size of the menu and icons (long? had to remove overflow-hidden on the webview element)
- Should we apply it to all screens? (How to do that??)
- Looking forward to the comments.
The menu can be applied to any websites.
Here is a video on how to test: 
https://github.com/responsively-org/responsively-app/assets/1730624/9986dc57-193a-4783-b093-aaed16611691
=> Accessibility

desktop-app/package.json, desktop-app/src/renderer/components/DropDown/index.tsx, desktop-app/src/renderer/context/ThemeProvider/index.tsx, desktop-app/yarn.lock
This fixes the hidden Dropdown flyout when wrapped in an overflow-hidden parent.
=> Dropdown flyout is rendered via portal

desktop-app/src/renderer/components/ToolBar/Shortcuts/ShortcutsModal/ShortcutButton.tsx
Fixes: #1185 
Currently for all the platform, shortcut mod is key visible as '⌘'. It should be Ctrl for windows devices.
=> fix: show ctrl as mod button in shortcut modal for windows devices

desktop-app/src/renderer/components/DeviceManager/PreviewSuites/index.tsx, desktop-app/src/renderer/components/Previewer/index.tsx, desktop-app/src/renderer/components/ToolBar/index.tsx
Based on user feedback on Discord, adding a button to make the device manager easily identifiable. 
Screenshot
=> Add device button added to the preview area

desktop-app/jest.config.js, desktop-app/package.json, desktop-app/setupTests.js, desktop-app/src/renderer/components/Button/Button.test.tsx, desktop-app/src/renderer/components/DeviceManager/PreviewSuites/ManageSuitesTool/ManageSuitesTool.test.tsx, desktop-app/src/renderer/components/DeviceManager/PreviewSuites/ManageSuitesTool/helpers.test.tsx, desktop-app/src/renderer/components/FileUploader/FileUploader.tsx
This PR does the following:
- extracts jest config from the package.json
- adds global mocks for electron and intersection obserer so components can be tested more easily.
- adds the command `yarn test:watch yourfile.test.tsx` -> it watches the test so when you save it runs it again automatically 
- adds the command `yarn test:coverage yourfolder/` -> it checks what lines are lacking test coverage in which files
- adds missing tests for the settings import/export feature, button and some other utils
Extract jest config and add it to the script. It also adds yarn `test:watch` to watch files while developing tests.
Usage: `yarn test:watch desktop-app/src/renderer/components/DeviceManager/PreviewSuites/ManageSuitesTool/utils.test.ts`
=> [Tests] extract jest config to file, add jest commands, add mocks and add missing tests

browser-extension/package.json, browser-extension/src/popup.js, browser-extension/webpack.config.js, desktop-app-legacy/app/components/LiveCssEditor/index.js
solving issue #1255
This project implements Hot Module Replacement (HMR) for a React-based Chrome extension, allowing developers to see real-time changes in their popup component without needing to refresh the entire extension. The following outlines the configuration and structure necessary for achieving this setup.
1. **Webpack Configuration (`webpack.config.js`)**:
- Configures Webpack for development and production modes, specifying the entry point and output settings.
- Enables HMR in the development server for instant updates.
2. **Entry Point (`src/popup.js`)**:
- Contains the main logic for the popup component, integrating the HMR logic to allow for module updates without a full reload.
3. **Index File (`src/index.js`)**:
- Updated to support HMR with checks for `module.hot`, …
=> Hot Module Replacement (HMR) Integration

desktop-app/src/renderer/components/ToolBar/AddressBar/index.tsx
#1272 
This pull request addresses the issue where clicking on the search bar in the Responsively App only places the cursor at the clicked position instead of selecting the entire URL. The update ensures that clicking the search bar will now select the entire URL.
https://github.com/user-attachments/assets/b2bd8fd5-892b-4965-b636-129f82d50335
=> Selecting the url in searchbar when clicked first

desktop-app/src/main/main.ts
Fixes: #1184
Fixes: #837 
This PR adds a variable to pick up when the app has been initiated, so it only comes to the front when it is being opened for the first time, but not on refresh.
STR: 
- Open the app
- Open a page with hot loading (in this case, it's a simple html page with live server (VS code extension)
- Make a change, the responsively app should not be focused 
https://github.com/user-attachments/assets/c8234d3d-6736-4935-8e5a-37412d365936
=> Fixes #1184

desktop-app/src/common/deviceList.ts
This PR introduces the following updates to the devicelist.ts:
1.Added support for Galaxy Z Fold 5 with a screen size of 344x882, dpr: 1.
2.Added support for Asus Zenbook Fold with a screen size of 853x1280, dpr: 2.
3.Added support for Pixel 7 with a screen size of 412x915, dpr: 2.625.
Each device entry includes its specific properties like userAgent, capabilities, and device type (phone, tablet).
Tested the changes by simulating these devices in the responsive design mode of Google Chrome DevTools.
Verified touch and mobile capabilities for the Galaxy Z Fold 5 and Pixel 7.
Ensured that the Asus Zenbook Fold is categorized as a tablet with the appropriate touch capabilities.
=> Some new devices added to devicelist.ts

browser-extension/src/popup.js
🚀 Feature Request
📝 Description
Currently, the useEffect inside the URLOpenerNonChrome and URLOpenerChrome components contains asynchronous logic that is executed on every render. This can lead to unnecessary re-renders, especially if the component is rendered multiple times. By optimizing the code with useCallback and useMemo, we can improve the performance of the application, ensuring that certain computations are only executed when necessary.
✨ Describe the solution you'd like
Refactor the asynchronous logic into a useCallback:
The logic for querying tabs and checking the custom protocol URI should be wrapped in useCallback to prevent unnecessary recalculations on each render.
Utilize useMemo to optimize dependent computations:
Any computations inside useEffect that depend on props or …
=> Performance Improvement

desktop-app/src/renderer/components/Previewer/Device/index.tsx
Fixes #1306 
Add the event listener for handling the change in address bar if the click happens inside the browser without reloading or going to  a new page
https://github.com/user-attachments/assets/b5a1667b-be09-4dd0-a9ac-7d0d32faf074
=> Fix #1306 - Update address bar on clicking a link

README.md
Fixes: #1302
The desktop app link was not working because there was no project at https://github.com/responsively-org/responsively-app/projects/12?fullscreen=true. So, I have directly redirected the user to https://github.com/responsively-org/responsively-app/projects instead.
Before 
After
=> Update Roadmap to desktop link that is not working  README.md

desktop-app/package-lock.json, desktop-app/package.json, desktop-app/release/app/package-lock.json, desktop-app/release/app/yarn.lock, desktop-app/src/common/constants.ts, desktop-app/src/renderer/components/Masonry/MasonryLayout.tsx, desktop-app/src/renderer/components/Previewer/index.tsx, desktop-app/src/renderer/components/ToolBar/Menu/Flyout/index.tsx, desktop-app/yarn.lock
Added Masonry Layout to the app. Modified the existing components to compitable with the masonry layout.
=> Fixed the issue #1206

desktop-app/src/renderer/components/Previewer/Device/index.tsx
Fix #1210
Added checker for landscape mode before strict ("w-52") size of device. 
flex-shrink-0 is not needed because we have control over elements with overflow scroll.
But long-term I'd put all the layout settings (incl. Masonry Layout, Preview Layout) into one component. Now it's too easy to break the whole visual configuration with inappropriate css style
=> fix: Fix restricted device size to enable phones landscape

desktop-app/src/common/deviceList.ts
Pull Request: Added iPhone 17 Models to Device List
Fix: #1419 
ℹ️ About the PR
This PR adds the anticipated iPhone 17 models to the device list based on industry projections and Apple's typical release patterns. The implementation includes:
⭐Four new iPhone 17 models: iPhone 17, iPhone 17 air, iPhone 17 Pro, and iPhone 17 Pro Max
The implementation follows the existing pattern in the codebase while adding future-looking device specifications that will help developers test their responsive designs against anticipated screen sizes.
Testing Performed and Passed✅
Screenshot of new devices:
=> Added New iPhone 17 Versions
