responsively-org/responsively-app

website/pages/assets/css/theme.css

Added scroll behavior CSS for smooth transitions when user clicks the header nav links.

Added scroll behavior css

---

README.md

add the brew cask install command in README

add brew link

---

desktop-app/app/actions/browser.js

Hi @manojVivek 
regarding this issue [https://github.com/manojVivek/responsively-app/issues/125](https://github.com/manojVivek/responsively-app/issues/125), please help to review
Thanks

fix: add new device when set preview active

---

desktop-app/app/menu.js
desktop-app/app/utils/generalUtils.js

Related to #120 
This "About" dialog is highly inspired by vscode's

Add "Help -> About" menu

---

desktop-app/app/actions/browser.js

Prevent reloading when only URL hash change, Fixes #100

---

desktop-app/app/actions/browser.js
desktop-app/app/components/Addressinput/index.js
desktop-app/app/components/DeviceManager/AddDevice/index.js
desktop-app/app/components/DeviceManager/DeviceItem/index.js
desktop-app/app/components/DeviceManager/DeviceItem/styles.css
desktop-app/app/components/DeviceManager/DeviceList/index.js
desktop-app/app/components/DeviceManager/DeviceList/styles.css
desktop-app/app/components/DeviceManager/index.js
desktop-app/app/components/DeviceManager/styles.css
desktop-app/app/components/HttpAuthDialog/index.js
desktop-app/app/components/WebView/index.js
desktop-app/app/constants/chromeEmulatedDevices.js
desktop-app/app/constants/devices.js
desktop-app/app/constants/settingKeys.js
desktop-app/app/main.dev.js
desktop-app/app/reducers/browser.js
desktop-app/app/settings/migration.js

This PR resolves the items listed in #140.

Device Manager improvements, Fixes #140

---

desktop-app/app/containers/Root.js
desktop-app/app/main.dev.js
desktop-app/app/menu.js
desktop-app/app/shortcut-manager/main-shortcut-manager.js
desktop-app/app/shortcut-manager/renderer-shortcut-manager.js
desktop-app/app/shortcut-manager/shared.js
desktop-app/app/shortcuts.html
desktop-app/package.json
desktop-app/yarn.lock

Using mousetrap instead
Automatically register menu items with accelerators
Fix main window losing focus when hotkeys dialog closes
related to #90 
rewrote of #166

Develop shortcut managers without globalShortcut or localShortcut

---

desktop-app/app/containers/Root.js
desktop-app/app/menu.js
desktop-app/app/shortcut-manager/renderer-shortcut-manager.js
desktop-app/app/shortcuts.html

register a lot of shortcuts
- Zoom In
- Zoom Out
- Zoom Reset
- Edit URL
- Scroll Up
- Scroll Down
- Take Screenshot
- Tilt Devices
- Toggle Inspector
- Go to Homepage
- Back a Page
- Forward a Page
- Delete Storage
- Delete Cookies
solve #90

register a lot of shortcuts

---

desktop-app/app/components/Addressinput/style.css

updated address bar so that the floating icons and url does not overlap

---

desktop-app/app/components/WebView/index.js

As said in #164, we just needed to check `isMainFrame` in the `did-navigate-in-page` event handler.
Also some space where removed in the code during the commit, sorry 😬 
fix #164

Fix app automatically navigating to iframe URL

---

desktop-app/app/app-updater.js
desktop-app/app/main.dev.js
desktop-app/app/menu.js

add check for updates menu item

---

desktop-app/app/app.global.css
desktop-app/app/shortcuts.html

As the issue #194 that I reported a while ago. This make the scrollbar appear consistent with the UI of the app.
Before 
After

Scrollbar update to match app's user interface

---

desktop-app/app/components/WebView/index.js

Changed the window 'scroll' event listener to a document 'scroll' listener.
Also changed the document.body 'mouse enter' and 'mouse leave' event listeners to document event listeners.

Changed mouseleave, mousein and scroll event listeners

---

README.md

changes on README.md

---

desktop-app/app/components/DevToolsResizer/style.module.css

resolves #257 
z-index did the trick 😉

increase z-index of devtools container

---

desktop-app/app/main.dev.js
desktop-app/app/reducers/browser.js
desktop-app/package.json

Do auto-reload the page, watching for the file changes, if a local HTML file is loaded in the browser

---

desktop-app/app/menu.js

- add Open Screenshots Folder menu item (#224)
- add Exit menu item
- add some separators

Improve app menu

---

website/pages/index.html

Heya! I just found a few typos and fixed them for you. Cheers!

docs: fix typos and inconsistencies in home page

---

desktop-app/app/components/StatusBar/index.js
desktop-app/app/components/StatusBar/styles.module.css
desktop-app/app/containers/Root.js
desktop-app/app/containers/StatusBarContainer/index.js

- You can now zoom using CTRL + wheel, 10% per 10% (if your cursor is out of a browser window)
- The zoom level is now displayed in the status bar so we can quickly glance at the zoom level

Allow zooming using mousewheel

---

desktop-app/app/components/Drawer/styles.css
desktop-app/app/components/UserPreferences/index.js
desktop-app/app/components/UserPreferences/styles.module.css
desktop-app/app/components/WebView/index.js
desktop-app/app/components/common.styles.css
desktop-app/app/reducers/browser.js

Add preference for adding an outline to devices

---

desktop-app/app/components/WebView/index.js
desktop-app/app/components/WebView/style.module.css

Device width bug fix

---

desktop-app/app/components/WebView/index.js
desktop-app/app/components/WebView/style.module.css

Fixed outline style for responsive device

---

desktop-app/app/components/WebView/index.js

feat(WebView): hide scrollbar on mobile devices

---

desktop-app/package-lock.json
desktop-app/package.json

Following [this](https://github.com/manojVivek/responsively-app/issues/318) issue I've successfully built and published app for rpm.  Please note that ``rpm-build`` package is required on the machine that runs ``npm run publish-linux``
Fixes: #318

Add rpm target

---

desktop-app/app/components/Addressinput/index.js
desktop-app/app/components/Addressinput/style.css
desktop-app/app/components/UrlSearchResults/index.js

UX adressbar  , `KeyDown` ,`KeyDown` , `Escape` #338

Ux addressbar

---

desktop-app/app/constants/chromeEmulatedDevices.js

Standardised Desktop devices

---

desktop-app/app/actions/browser.js
desktop-app/app/components/DevToolsResizer/index.js
desktop-app/app/components/DevToolsResizer/style.module.css
desktop-app/app/components/DeviceManager/index.js
desktop-app/app/components/WebView/index.js
desktop-app/app/constants/pubsubEvents.js
desktop-app/app/containers/DevToolResizerContainer/index.js
desktop-app/app/index.js
desktop-app/app/main.dev.js
desktop-app/app/reducers/bookmarks.js
desktop-app/app/reducers/browser.js
desktop-app/package.json
desktop-app/yarn.lock

Device drop down to switch device from devtools

---

desktop-app/app/components/Addressinput/index.js

feat(desktop-app): add file schema on address bar for filesystem paths

---

desktop-app/app/main.dev.js
desktop-app/app/menu.js
desktop-app/package-lock.json

automatic format filepath to file url

fix , file has an # in the name, it does not open with responsively

---

website/js/custom/contributors.js

Exclude bots from contributors list
before:
after:

exclude bots from contributors

---

desktop-app/app/components/DeviceManager/AddDevice/index.js
desktop-app/app/components/DeviceManager/DeviceList/index.js
desktop-app/app/components/DeviceManager/DeviceList/styles.css
desktop-app/app/components/DeviceManager/index.js

resolves #234 
also this PR fix some style issues when adding new devices

Keep inactive devices order on device management

---

desktop-app/app/main.dev.js
desktop-app/app/menu.js
desktop-app/app/utils/generalUtils.js
desktop-app/package.json
desktop-app/yarn.lock

encapsulate get environment info to access from main and renderer processes

Encapsulate get environment info

---

desktop-app/app/components/ErrorBoundary/index.js

Allow user to select error info on app crash until we merge #411

Allow user to select error info on app crash

---

desktop-app/package.json

Add electron builder config to remove app data on uninstall

---

README.md

Improve contribute section on README

---

desktop-app/app/app-updater.js
desktop-app/app/components/StatusBar/index.js
desktop-app/app/menu.js
desktop-app/package.json

handle updates checking logic
resolves #439

Add windows portable version to electron-builder config

---

desktop-app/app/components/Addressinput/index.js

Assume HTTP for localhost subdomains

---

desktop-app/app/components/Header/index.js
desktop-app/app/components/PermissionPopup/index.js
desktop-app/app/components/PermissionPopup/styles.module.css

Re-add permissions prompt
Update styles for light theme

Re-add permissions prompt

---

desktop-app/app/components/Header/index.js

Bookmarks row is not in the right position

Fix bookmarks row position

---

desktop-app/app/components/WebView/index.js

Fix responsive devices handle bars on zoom != 100%

---

desktop-app/app/components/LeftIconsPane/index.js
desktop-app/app/components/NetworkProxy/ProxyManager/index.js
desktop-app/app/components/NetworkThrottling/ProfileManager/index.js
desktop-app/app/components/NetworkThrottling/ProfileManager/styles.css
desktop-app/app/components/ScreenShotSavePreference/index.js
desktop-app/app/components/Select.js

Fixed some styles:
- Left Pane icons vertical alignment:
Before:
After:
- Proxy Manager
Before:
After:
- Throttling Profiles Manager
Before:
After:
- Screenshot Save path
Before:
After:
- Select styles on light theme (use same border-color as material's TextField)
Before:
After:

fix some styles

---

desktop-app/app/components/AppNotification/AppNotification.js
desktop-app/package.json

Hotfix for app crash

---

desktop-app/app/actions/networkConfig.js
desktop-app/app/main.dev.js
desktop-app/flow-typed/electron.js

Start responsively maximized

---

README.md

Add choco install info in README

---

.github/ISSUE_TEMPLATE/01-bug-report.md
.github/ISSUE_TEMPLATE/02-feature-request.md
.github/PULL_REQUEST_TEMPLATE.md

**What does this PR contain?**
Adds the following,
- Bug Report Template
- Feature Request template
- Pull Request Template

doc: add issue and pull request template

---

desktop-app/app/components/Renderer/index.js
desktop-app/app/components/WebView/index.js

NA
This PR is to clean up the crowded toolbar above the devices.
Before:
After:

Device toolbar cleanup

---

desktop-app/app/components/ExtensionsManager/index.js
desktop-app/app/components/ExtensionsManager/styles.css

Resolves #514 
fixes some styles

Fix extension helper popup

---

desktop-app/app/components/WebView/index.js

Hotfix / Fixed the broken global flip button

---

desktop-app/app/constants/chromeEmulatedDevices.js

Resolves #525 
- Update user-agent for some iPhone-like devices
- Add new devices: Moto G4, Surface Duo, and Galaxy Fold
info source: [chromium source code](https://source.chromium.org/chromium/chromium/src/+/master:third_party/devtools-frontend/src/front_end/emulated_devices/module.json?q=emulated_devices%2Fmodule.json&ss=chromium)

Update built-in devices

---

desktop-app/app/constants/settingKeys.js
desktop-app/app/reducers/browser.js
desktop-app/app/settings/migration.js

Resolves #534 
I edited ./desktop-app/app/constants/settingKeys.js and ./desktop-app/app/reducers/browser.js
This is my second PR in my life!
I'm not sure this is right.
if I changed Layout setting to "HORIZONTAL",
I could find that Layout setting is still "HORIZONTAL".
I also tested two remainings.

Save Layout settings

---

desktop-app/app/components/icons/FullScreenshot.js

#547 Typo error in function name
This simple pull request is to fix the assumed spelling error of a function named "FullScreenShort".
I can not find any other file that is referencing this exported function.
This is not a bug fix, or feature addition and there are no visible changes to the product.
The change is only visible when looking at the source code.

#547 Typo in function name

---

desktop-app/app/components/LeftIconsPane/index.js

Added tooltip to icons on the left panel. At first, it could be confusing what it means. Now is clear and accessible.

Add tooltip to icons on left panel

---

desktop-app/app/components/WebView/index.js

Fixes #563 
The vulnerability was that local file content can be accessed by a remote page. Made a fix by checking the parent and current URL protocols.

Fixing the vulnerability where local files contents can be accessed by a remote page

---

desktop-app/app/components/AddressInput.js
desktop-app/app/components/WebView/index.js
desktop-app/app/main.dev.js
desktop-app/app/reducers/browser.js
desktop-app/app/utils/urlUtils.js

resolves #369
and maybe, just _maybe_ #365 
Set `process.argv[1]` as `urlToOpen` if no url or file has been set to open.
As part of this PR I had to change the place in the code where the initial URL is set and as a consequence it is _possible_ that #343 has been resolved (at least an improvement should be appreciated) 
I tested this on Windows only, it should be tested on other OS too

Allow pass url/filepath from cli args

---

desktop-app/app/components/Drawer.js
desktop-app/app/components/UserPreferences/index.js
desktop-app/app/services/searchUrlSuggestions/index.js

resolves #341
Add a button on User Settings menu as suggested

Add Clear Address History button to User Settings Menu

---

.gitignore

Git ignore .vscode

---

.gitignore

Reverts responsively-org/responsively-app#262

Revert "Git ignore .vscode"

---

desktop-app/app/constants/chromeEmulatedDevices.js

Added iPhone 12/13 Pro Max & iPhone 12/13 Pro, based on specs from https://blisk.io/devices.
Partly addresses #667.

Added iPhone 12/13 Pro Max & iPhone 12/13 Pro

---

desktop-app-rewrite/src/renderer/components/Previewer/Device/index.tsx

Devices size discripancy fix

---

desktop-app-rewrite/src/renderer/components/Previewer/index.tsx

v1: Unnecessary scrollbars fixed

---

.github/workflows/publish.yml
desktop-app-rewrite/release/app/package.json

ci: App release workflow with auto version bump and manual trigger only

---

desktop-app-rewrite/.erb/configs/webpack.config.main.prod.ts

Fix for https://github.com/responsively-org/responsively-app/issues/724#issuecomment-1300096374

hotfix: Broken event mirroring fix

---

desktop-app-rewrite/src/main/native-functions/index.ts
desktop-app-rewrite/src/renderer/components/ToolBar/ColorSchemeToggle/index.tsx
desktop-app-rewrite/src/renderer/components/ToolBar/index.tsx
desktop-app-rewrite/yarn.lock

v1: Device theme color scheme toggle

---

desktop-app-rewrite/src/main/main.ts
desktop-app-rewrite/src/main/web-permissions/PermissionsManager.ts
desktop-app-rewrite/src/main/web-permissions/index.ts
desktop-app-rewrite/src/renderer/components/Button/index.tsx
desktop-app-rewrite/src/renderer/components/ToolBar/AddressBar/index.tsx
desktop-app-rewrite/src/renderer/components/ToolBar/NavigationControls.tsx
desktop-app-rewrite/src/renderer/preload.d.ts
desktop-app-rewrite/src/renderer/store/features/renderer/index.ts
desktop-app-rewrite/src/store/index.ts

v1: Permission requests

---

desktop-app-rewrite/src/main/main.ts
desktop-app-rewrite/src/main/menu.ts
desktop-app-rewrite/src/main/web-permissions/PermissionsManager.ts
desktop-app-rewrite/src/main/web-permissions/index.ts
desktop-app-rewrite/src/renderer/components/Previewer/Device/index.tsx
desktop-app-rewrite/src/renderer/components/Previewer/Device/utils.ts
desktop-app-rewrite/src/renderer/components/ToolBar/AddressBar/SuggestionList.tsx
desktop-app-rewrite/src/renderer/components/ToolBar/AddressBar/index.tsx
desktop-app-rewrite/src/renderer/components/ToolBar/Menu/Flyout/ClearHistory/index.tsx
desktop-app-rewrite/src/renderer/components/ToolBar/Menu/Flyout/index.tsx
desktop-app-rewrite/src/renderer/store/features/renderer/index.ts
desktop-app-rewrite/src/store/index.ts

v1: Address bar suggestions

---

desktop-app/package.json
desktop-app/src/common/deviceList.ts
desktop-app/src/renderer/components/Button/index.tsx
desktop-app/src/renderer/components/DeviceManager/DeviceDetailsModal.tsx
desktop-app/src/renderer/components/DeviceManager/DeviceLabel.tsx
desktop-app/src/renderer/components/DeviceManager/index.tsx
desktop-app/src/renderer/components/Input/index.tsx
desktop-app/src/renderer/components/Modal/index.tsx
desktop-app/src/renderer/components/Select/index.tsx
desktop-app/src/renderer/context/ThemeProvider/index.tsx
desktop-app/src/renderer/store/features/device-manager/index.ts
desktop-app/src/store/index.ts
desktop-app/yarn.lock

v1: Device Manager - Add, edit and delete custom devices

---

desktop-app/src/common/constants.ts
desktop-app/src/main/http-basic-auth/index.ts
desktop-app/src/main/main.ts
desktop-app/src/main/preload-webview.ts
desktop-app/src/main/preload.ts
desktop-app/src/main/web-permissions/PermissionsManager.ts
desktop-app/src/renderer/components/ToolBar/AddressBar/AuthModal.tsx
desktop-app/src/renderer/components/ToolBar/AddressBar/index.tsx
desktop-app/src/renderer/index.tsx
desktop-app/src/renderer/preload.d.ts

v1: Basic Auth Support

---

desktop-app/package.json
desktop-app/src/common/constants.ts
desktop-app/src/common/deviceList.ts
desktop-app/src/renderer/components/Previewer/index.tsx
desktop-app/src/renderer/components/ToolBar/Menu/Flyout/PreviewLayout/index.tsx
desktop-app/src/renderer/components/ToolBar/Menu/Flyout/index.tsx
desktop-app/src/renderer/store/features/renderer/index.ts
desktop-app/src/store/index.ts

v1: Preview layout modes, default devices refined and minor UI polish

---

desktop-app/package.json
desktop-app/src/common/constants.ts
desktop-app/src/main/app-meta/index.ts
desktop-app/src/main/main.ts
desktop-app/src/main/screenshot/index.ts
desktop-app/src/renderer/AppContent.tsx
desktop-app/src/renderer/components/ReleaseNotes/index.tsx
desktop-app/src/store/index.ts
desktop-app/tailwind.config.js
desktop-app/yarn.lock

v1: Release notes dialog

---

desktop-app/src/main/devtools/index.ts
desktop-app/src/main/web-permissions/PermissionsManager.ts

Fixed the mac bug when app can't be opened if not exiting after closing a window

---

desktop-app/src/main/app-meta/index.ts
desktop-app/src/renderer/components/ToolBar/AddressBar/SuggestionList.tsx
desktop-app/tailwind.config.js

Event mirroring bug fix

---

desktop-app/src/renderer/context/ThemeProvider/index.tsx
desktop-app/tailwind.config.js

Device manager overflow background fix

---

desktop-app/declarations.d.ts
desktop-app/package.json
desktop-app/src/common/constants.ts
desktop-app/src/main/cli.ts
desktop-app/src/main/main.ts
desktop-app/src/main/util.ts
desktop-app/src/renderer/components/ToolBar/AddressBar/index.tsx
desktop-app/yarn.lock

Handling Cli args to support passing URLs to open via cli

---

desktop-app/package.json
desktop-app/src/main/devtools/index.ts
desktop-app/src/main/util.ts
desktop-app/src/renderer/AppContent.tsx
desktop-app/yarn.lock

Electron version upgrade and fixes

---

desktop-app/src/common/deviceList.ts

Partly addresses #667
Added a new device

Added Samsung S21 FE

---

desktop-app/src/main/menu.ts
desktop-app/src/main/util.ts

Added about in help menu

---

desktop-app/package.json
desktop-app/release/app/package.json
desktop-app/src/main/menu.ts

Resolves https://github.com/responsively-org/responsively-app/issues/813#issuecomment-1437415162

Fixed the about menu in non-mac environments

---

desktop-app/src/renderer/store/features/renderer/index.ts
desktop-app/src/store/index.ts

Zoom level persisted across restarts

---

desktop-app/src/renderer/components/Previewer/Device/index.tsx

fixed: Refresh button only refreshes first device

---

desktop-app/src/common/constants.ts
desktop-app/src/main/main.ts
desktop-app/src/main/protocol-handler/index.ts

Handling custom protocol `responsively://`

---

desktop-app/src/common/webViewUtils.ts
desktop-app/src/main/screenshot/index.ts
desktop-app/src/renderer/components/ModalLoader/index.tsx
desktop-app/src/renderer/components/Previewer/Device/Toolbar.tsx
desktop-app/src/renderer/components/ToolBar/index.tsx
desktop-app/src/renderer/store/features/renderer/index.ts

Allows screen shot of all the screens
Fixes #917 
- Adds Device name to the screenshot 
- Gives a button to capture screenshot of all devices
- Users existing screenshot flow to capture screens

Feature screenshot all views

---

desktop-app/src/renderer/store/features/device-manager/index.ts

Preview suites defensive fix

---

desktop-app/src/common/deviceList.ts
desktop-app/src/renderer/components/DeviceManager/DeviceDetailsModal.tsx
desktop-app/src/renderer/components/DeviceManager/index.tsx
desktop-app/src/renderer/store/features/device-manager/index.ts
desktop-app/src/renderer/store/features/device-manager/utils.ts

Fixed the crash when a custom device is added to the preview for the first time

---

desktop-app/src/main/main.ts

Suppressed 'ready-to-show' events from webview to prevent unnecessary window focus stealing

---

desktop-app/src/renderer/components/Button/index.tsx
desktop-app/src/renderer/components/ReleaseNotes/index.tsx

ui: Tweaked the color/design for the release notes dialog

---

desktop-app/src/renderer/components/Previewer/Device/index.tsx

Webview user agent string fixed

---

desktop-app/src/renderer/components/DeviceManager/DeviceDetailsModal.tsx
desktop-app/src/renderer/components/DeviceManager/index.tsx

Device manager crash fix

---

README.md

As a future user I want to find the downloads fast :-)
It took me a minute to find the correct location to download - this should reduce this to seconds.

README: Improve the way to the downloads

---

README.md

Issue #1032 
On readme.md logo link was broken, it's changed with new one.

logo is down issue fixed #1032

---

desktop-app/src/main/screenshot/index.ts
desktop-app/src/renderer/components/ToolBar/Menu/Flyout/Bookmark/index.tsx
desktop-app/src/renderer/components/ToolBar/Menu/Flyout/Settings/SettingsContent.tsx
desktop-app/src/renderer/components/ToolBar/Menu/Flyout/Settings/index.tsx
desktop-app/src/renderer/components/ToolBar/Menu/Flyout/index.tsx
desktop-app/src/renderer/components/ToolBar/Menu/index.tsx
desktop-app/src/store/index.ts

User preference option to configure screenshot save location

---

desktop-app/src/common/deviceList.ts

Should be MacBook instead of Macbook. See https://www.apple.com/macbook-pro/

Fix MacBook capitalization in deviceList.ts

---

README.md

Refs #1107 
Changed the previous contributing instructions (that were short) in the `README.md` file, to an instruction & a link which leads the user to the detailed contribution guidelines file, `CONTRIBUTING.md`.

Linked CONTRIBUTING.md to the main README.md

---

desktop-app/src/main/main.ts

Extension deep link bug fix

---

CONTRIBUTING.md

Add more info about working on issues

Add extra information to contributing guidelines

---

desktop-app/package.json
desktop-app/src/renderer/components/Previewer/Device/index.tsx

Show the error overlay only for mainframe errors
